const stringTables = {
    en: {
        header_services: "SERVICES",
        header_about: "ABOUT",
        header_contact: "CONTACT",
        services_title: "SERVICES",
        services_title_infomgmt: "INFORMATION MANAGEMENT",
        services_content_infomgmt: "Management and coordination of digital assets, data and consultancy on process and implementation of information management systems for hyperscale data centers, residential and specialist infrastructure.",
        read_more: "READ MORE",
        services_title_om: "O&M MANUALS",
        services_content_om: "Maintaining a high quality building often requires a stellar foundation of information. We manage the manual process to ensure your operations team start on steady ground.",
        services_title_reporting: "REPORTING & ANALYTICS",
        services_content_reporting: "Tracking closeout, analysis of pain points and clear, easy to digest dashboards to ensure that you have the information needed to accurately pinpoint documentation progress.",
        about_title: "ABOUT NODEHEX",
        about_p1: "Nodehex is an information management specialist group for hyperscale data centers and commercial builds. Our team has a wealth of experience delivering and managing documentation services across a vast number of hyperscale datacenter projects and the specialist infrastructure, offices and ancillary buildings that enable them. We simplify the process by removing the ambiguity around documentation, understanding client needs and requirements and then implementing a structure to ensure a lasting impression for information management across all mission-critical systems.",
        about_p2: "Our services focus on providing a high quality, data driven and front-loaded effort to ensure an effective delivery from design to decommissioning. This being combined with support into the first year of operations, a smooth transition and high-quality documentation for the operations team to execute on, a facility is only as good as the information it’s supported by.",
        why_title: "WHY NODEHEX",
        why_p1: "Nodehex is a multi-disciplinary, multi-cultural team of information management specialists, data scientists, software developers and designers that have been working within the construction and technology industries over the last 10 years.",
        why_p2: "Our expertise has been developed over large scale infrastructure projects, specialist hyperscale data center buildings and specialist facilities. We aim to leverage emerging technologies within the digital construction sector to extract the immense value of the data contained within projects and provide expertise consultancy on process and information management.",
        contact_title: "CONTACT",
        contact_name: "Name",
        contact_email: "Email",
        contact_subject: "Subject",
        contact_message: "Message",
        footer_tagline: "Construction data, digitalised",
        footer_general: "General",
        footer_services: "Services",
        footer_infomgmt: "INFORMATION MANAGEMENT",
        footer_reporting: "REPORTING & ANALYTICS",
        footer_om: "OPERATIONS & MAINTENANCE MANUALS",
        footer_about: "ABOUT",
        footer_contact: "CONTACT NODEHEX",
        footer_privacy: "PRIVACY"
    },
    nl: {
        header_services: "DIENSTEN",
        header_about: "",
        header_contact: "",
        services_title: "",
        services_title_infomgmt: "",
        services_content_infomgmt: "",
        read_more: "",
        services_title_om: "",
        services_content_om: "",
        services_title_reporting: "",
        services_content_reporting: "",
        about_title: "",
        about_p1: "",
        about_p2: "",
        why_title: "",
        why_p1: "",
        why_p2: "",
        contact_title: "",
        contact_name: "",
        contact_email: "",
        contact_subject: "",
        contact_message: "",
        footer_tagline: "",
        footer_general: "",
        footer_services: "",
        footer_infomgmt: "",
        footer_reporting: "",
        footer_om: "",
        footer_about: "",
        footer_contact: "",
        footer_privacy: ""
    },
    se: {
        header_services: "TJÄNSTER",
        header_about: "OM",
        header_contact: "KONTAKT",
        services_title: "TJÄNSTER",
        services_title_infomgmt: "INFORMATIONSHANTERING",
        services_content_infomgmt: "Hantering och koordinering av digitala tillgångar, data och rådgivning gällande processer och implementering av informationshanteringssystem för datacenter i hyperskala, bostads- och specialistinfrastruktur.",
        read_more: "LÄS MER",
        services_title_om: "DoU-MANUALER",
        services_content_om: "Underhåll av högkvalitativa byggnader kräver ofta enastående grundinformation. Vi hanterar manualprocessen och säkrar att er driftavdelning står på stadig grund.",
        services_title_reporting: "RAPPORTER & ANALYSER",
        services_content_reporting: "Spårning av utförsäljning, analyser av nyckelpunkter och tydliga, lättsmälta informationspaneler säkerställer att ni har informationen ni behöver för att noga följa dokumentationens utveckling.",
        about_title: "OM NODEHEX",
        about_p1: "Nodehex är en specialistgrupp för informationshantering av datacenter i hyperskala och kommersiella byggprojekt. Vårt team har bred erfarenhet av att leverera och hantera dokumentationstjänster för ett stort antal projekt inom datacenter i hyperskala samt den specialistinfrastruktur, de kontor och övriga kringliggande byggnader som möjliggör dem. Vi simplifierar processen genom att förstå kundbehov och krav samt ta bort oklarheter kring dokumentation för att implementera en struktur som säkerställer ett bestående intryck av informationshanteringen genom alla uppdragskritiska system.",
        about_p2: "Våra tjänster fokuserar på att tillhandahålla en högkvalitativ, datadriven och framtung insats för att säkerställa effektiv leverans från design till avveckling. Detta kombineras med support under första driftåret, en smidig övergång till högkvalitativ dokumentation för driftavdelningen att använda, en anläggning är bara så bra som informationen den understöds av.",
        why_title: "VARFÖR NODEHEX",
        why_p1: "Nodehex är ett tvärvetenskapligt, multikulturellt team av informationshanteringsspecialister, datavetare, mjukvaruutvecklare och formgivare som har arbetat inom bygg- och IT-branscherna under de senaste 10 åren.",
        why_p2: "Vår expertis har utvecklats genom storskaliga infrastrukturprojekt, byggnader för datacenter i hyperskala och specialistanläggningar. Vi strävar efter att utnyttja framväxande teknologier inom den digitala byggsektorn för att extrahera det enorma värde av projektdatat och tillhandahålla expertkonsultation av process- och informationshantering.",
        contact_title: "KONTAKT",
        contact_name: "Namn",
        contact_email: "E-post",
        contact_subject: "Ämne",
        contact_message: "Meddelande",
        footer_tagline: "Construction data, digitalised",
        footer_general: "Allmänt",
        footer_services: "Tjänster",
        footer_infomgmt: "INFORMATIONSHANTERING",
        footer_reporting: "RAPPORTER & ANALYSER",
        footer_om: "DoU-MANUALER",
        footer_about: "OM",
        footer_contact: "KONTAKTA NODEHEX",
        footer_privacy: "INTEGRITET"
    }
}