const stringTables = {
    en: {
        title_index: "Nodehex",
        title_infomgmt: "Nodehex - Information Management",
        title_om: "Nodehex - Operation and Maintenance Manuals",
        title_reporting: "Nodehex - Reporting and Analytics",
        title_privacy: "Nodehex - Privacy Policy",
        header_services: "SERVICES",
        header_about: "ABOUT",
        header_contact: "CONTACT",
        header_home: "HOME",
        services_title: "SERVICES",
        services_title_infomgmt: "INFORMATION MANAGEMENT",
        services_content_infomgmt: "Management and coordination of digital assets, data and consultancy on process and implementation of information management systems for hyperscale data centers, residential and specialist infrastructure.",
        read_more: "READ MORE",
        services_title_om: "O&M MANUALS",
        services_content_om: "Maintaining a high quality building often requires a stellar foundation of information. We manage the manual process to ensure your operations team start on steady ground.",
        services_title_reporting: "REPORTING & ANALYTICS",
        services_content_reporting: "Tracking closeout, analysis of pain points and clear, easy to digest dashboards to ensure that you have the information needed to accurately pinpoint documentation progress.",
        about_title: "ABOUT NODEHEX",
        about_p1: "Nodehex is an information management specialist group for hyperscale data centers and commercial builds. Our team has a wealth of experience delivering and managing documentation services across a vast number of hyperscale datacenter projects and the specialist infrastructure, offices and ancillary buildings that enable them. We simplify the process by removing the ambiguity around documentation, understanding client needs and requirements and then implementing a structure to ensure a lasting impression for information management across all mission-critical systems.",
        about_p2: "Our services focus on providing a high quality, data driven and front-loaded effort to ensure an effective delivery from design to decommissioning. This being combined with support into the first year of operations, a smooth transition and high-quality documentation for the operations team to execute on, a facility is only as good as the information it’s supported by.",
        why_title: "WHY NODEHEX",
        why_p1: "Nodehex is a multi-disciplinary, multi-cultural team of information management specialists, data scientists, software developers and designers that have been working within the construction and technology industries over the last 10 years.",
        why_p2: "Our expertise has been developed over large scale infrastructure projects, specialist hyperscale data center buildings and specialist facilities. We aim to leverage emerging technologies within the digital construction sector to extract the immense value of the data contained within projects and provide expertise consultancy on process and information management.",
        contact_title: "CONTACT",
        contact_name: "Name",
        contact_email: "Email",
        contact_subject: "Subject",
        contact_message: "Message",
        footer_tagline: "Construction data, digitalised",
        footer_general: "General",
        footer_services: "Services",
        footer_infomgmt: "INFORMATION MANAGEMENT",
        footer_reporting: "REPORTING & ANALYTICS",
        footer_om: "OPERATIONS & MAINTENANCE MANUALS",
        footer_about: "ABOUT",
        footer_contact: "CONTACT NODEHEX",
        footer_privacy: "PRIVACY",
        infomgmt_intro: "Nodehex has worked within the information management sector for the last decade, covering the wide range of deliverables and expertise within the field from data quality, system implementation to large scale reporting and analytics. Our  have a multidisciplinary approach that combines digital construction expertise with data science and software development to guarantee that we deliver high quality results based on the dynamic needs of your projects.",
        infomgmt_cims_header: "Core information management services",
        infomgmt_cims_text: "Our services focus on digital construction delivery throughout the entire lifecycle of a project, broken down into three core competencies, project initialisation, reporting and handover services.",
        infomgmt_pis_header: "Project Initialisation Services",
        infomgmt_pis_text: "Handover is often left as a final checkbox once the final phases of construction and commissioning are nearing their completion, rather than front-loaded effort that kicks off at design. A majority of the issues during handover can often be mitigated by an experienced information management team developing the correct plans, processes and procedures, which then enables a progressive handover, rather than a massive end of project task.",
        infomgmt_edms_header: "Electronic Document Management Systems",
        infomgmt_edms_text_intro: "Our team has experience of over 15 of the industry leading EDMS at an administrator and developer level, which is a critical component to any major project and effective management of digital information. Our services cover the following areas of an EDMS implementation:",
        infomgmt_edms_header2: "Our services cover the following areas of an <span class=\"yellow-text\">EDMS</span> implementation:",
        infomgmt_edms_li1: "Entire project level set-up and development.",
        infomgmt_edms_li2: "Subject matter expert training, development and delivery.",
        infomgmt_edms_li3: "Project team training based on needs/use case assessment.",
        infomgmt_edms_li4: "Core metadata requirements for all stakeholders at multiple levels, client, contractor and sub-contractor.",
        infomgmt_edms_li5: "Full deliverable pre-population at early project stage to enable accurate and clear reporting.",
        infomgmt_edms_li6: "Standardised workflows based on industry best practice.",
        infomgmt_dmp_header: "Document Management Plans",
        infomgmt_dmp_text_intro: "Our team has experience authoring, reviewing, approving and implementing document management across largescale projects. We understand client needs, your requirements and translate them into effective processes and procedures for the execution of the project. To do this we:",
        infomgmt_dmp_li1: "Fully authored Document Management Plan inclusive of client requirements and coordination of the review and approval process.",
        infomgmt_dmp_li2: "Breakdown and detailing of core system set up and requirements, workflows, management requirements and handover processes within the plan.",
        infomgmt_dmp_li3: "Provide visual workflows to convey the project processes concisely.",
        infomgmt_dihihc_header: "Master Deliverable Index, Handover Index and Handover coordination",
        infomgmt_dihihc_text: "Understanding delivery of information is core to holding vendors, suppliers and subcontractors accountable for handover. Getting these processes in place and executed during the early phases of the project guarantees a low-effort handover and visible accountability.",
        infomgmt_mitigate_text_intro: "To mitigate late delivery and overdue handover risk we:",
        infomgmt_mitigate_li1: "Initiate the <span class=\"yellow-text\">Master Deliverable Index</span> (MDI) and <span class=\"yellow-text\">Handover indexes</span> (HOI) and develop them continually as parallel actions from the outset of the project.",
        infomgmt_mitigate_li2: "Coordinate with the subcontractors to populate and develop the MDI to ensure full visibility and understanding across the board.",
        infomgmt_mitigate_li3: "Integrate with the commissioning teams to project and support the commissioning documentation and its handover.",
        infomgmt_mitigate_li4: "Coordinating the handover, including tracking of all PDF and native deliverables across numerous systems and into the client's repositories.",
        infomgmt_reporting_link: "For more of our reporting services, please navigate to our <a href=\"reporting-analytics.html\" class=\"content-link\">reporting and analytics service page</a>.",
        om_intro: "Operations and Maintenance Manuals are the cornerstone of a high-performance operations team. They’re comprehensive documents that provide all of the necessary details regarding the building systems and assets contained in those systems, within the Client’s datacenters and mission-critical infrastructure.",
        om_p1: "Given the ever-growing scope of information management and its application in leveraging data for increased value to Design, Construction, Commissioning and Owner teams, it’s imperative to identify and more importantly, improve on data collection for operations and maintenance manuals. During a hyperscale datacenter build, the sheer amount of information produced can be staggering and finding effective ways to manage the data into handover - especially when modern hyperscale datacenter handover packages often consist of up to 50,000 documents or more - can be a challenge.",
        om_p2: "Coordinating and staggering this information across a project takes a knowledge of the phasing for a hyperscale datacenter and ancillary buildings, such as substations and utility buildings, a deep understanding of the information lifecycle the integration of quality and project management best practices at the right times to ensure an optimal outcome.",
        om_h5_1: "A typical O&M will include a wealth of information, typically based on systems within the building being operated, such as:",
        om_sysdesc_header: "System Description",
        om_sysdesc_text: "Design and construction intent of the system itself and the principles behind the operation of the system and the components contained therein.",
        om_spec_header: "Specification",
        om_spec_text: "Client specifications and requirements detailing the specific system information that supports the overall product needs",
        om_dmgd_header: "Drawing, Models and graphical data",
        om_dmgd_text: "References and embedded information pertaining to the outputs from the Design and Construction teams at the specified level of detail by from the Client's information requirements.",
        om_seqops_header: "Sequence of Operations",
        om_seqops_text: "Information pertaining to safe start up, systems operation within normal procedures and failsafe procedures and plant.",
        om_contact_link: "At Nodehex, we can author, maintain and implement a variety of solutions to ensure that handover, operations and beyond, the information to operate the systems within your project can be done both safely and efficiently. Whether this is a full authoring and coordination of information across a project, consolidating and updating existing manuals or bespoke solutions for your needs, <a href=\"index.html#contact\" class=\"content-link\">we can help</a>.",
        reporting_intro: "The immense value of datacenters is contained within their primary functions, the storing, processing and dissemination of data and critical applications. Where datacenters utilise data efficiently and are able to mine the value from this data, construction teams often fail to extract the complete potential of data generated during a project.",
        reporting_p1: "While the project controls teams often excel at managing cost, commercials and schedule, and there is often some analytics focused on BIM, Quality and Documentation, the full potential of these services are never actually realised. Often projects have a bulky and manual extract, transfer and load process that doesn’t offer flexibility and real-time reporting due to tool restraints, technical restraints and general lack of expertise in data science and implementation.",
        reporting_p2: "On any project, there are often a few systems at play that cover <span class=\"yellow-text\">BIM</span>, <span class=\"yellow-text\">Quality</span> and <span class=\"yellow-text\">Documentation</span>:",
        reporting_li_edms: "Electronic Document Management System (EDMS)",
        reporting_li_detc: "Documentum, Aconex, Viewpoint 4Projects, EnterpriseBridge, etc.",
        reporting_li_cde: "Common Data Environment (CDE)",
        reporting_li_bimproj: "BIM360, ProjectWise, Procore, BIMPLUS, etc.",
        reporting_li_comenv: "Commissioning environment",
        reporting_li_bimcom: "BIM360 Field, Commissioning trackers, etc",
        reporting_li_mprf: "Master Project Folders",
        reporting_li_extranet: "Cloud and extranet based folder structures, trackers, spreadsheets, etc.",
        reporting_p3: "Our teams have the experience and expertise to leverage application programming interfaces (APIs), Extraction, Transformation and Load (ETL) processes and fully automated, live reporting to ensure that you can demonstrate where key blockers and issues can be found, plus extract the additional value from these datasets that are often left behind in most projects.",
        reporting_p4: "On top of that, we provide compelling analytics and visualisations to ensure that the data we’ve extracted tells its story and provides clear and visible detail on where you are in the project, how your progressive handover is developing and where each detail can be found across the project data environment.",
        reporting_contact: "For further information, please <a href=\"index.html#contact\" class=\"content-link\">contact us</a> and we would be happy to develop a solution that fits your needs and requirements.",
        privacy_h1: "Privacy Policy for Nodehex",
        privacy_p1_1: "At Nodehex, accessible from https://nodehex.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Nodehex and how we use it.",
        privacy_p1_2: "If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.",
        privacy_p1_3: "This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Nodehex. This policy is not applicable to any information collected offline or via channels other than this website.",
        privacy_h2_1: "Consent",
        privacy_p2_1: "By using our website, you hereby consent to our Privacy Policy and agree to its terms.",
        privacy_h2_2: "Information we collect",
        privacy_p3_1: "The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.",
        privacy_p3_2: "If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.",
        privacy_h2_3: "How we use your information",
        privacy_p4_1: "We use the information we collect in various ways, including to:",
        privacy_li_1: "Provide, operate, and maintain our website",
        privacy_li_2: "Improve, personalize, and expand our website",
        privacy_li_3: "Understand and analyze how you use our website",
        privacy_li_4: "Develop new products, services, features, and functionality",
        privacy_li_5: "Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes",
        privacy_li_6: "Send you emails",
        privacy_li_7: "Find and prevent fraud",
        privacy_h2_4: "Log Files",
        privacy_p5_1: "Nodehex follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.",
        privacy_h2_5: "Cookies and Web Beacons",
        privacy_p6_1: "Like any other website, Nodehex uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.",
        privacy_p6_2: "For more general information on cookies, please read",
        privacy_p6_3: "more on the Cookie Consent website",
        privacy_h2_6: "Advertising Partners Privacy Policies",
        privacy_p7_1: "You may consult this list to find the Privacy Policy for each of the advertising partners of Nodehex.",
        privacy_p7_2: "Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Nodehex, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.",
        privacy_p7_3: "Note that Nodehex has no access to or control over these cookies that are used by third-party advertisers.",
        privacy_h2_7: "Third Party Privacy Policies",
        privacy_p8_1: "Nodehex's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.",
        privacy_p8_2: "You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.",
        privacy_h2_8: "CCPA Privacy Rights (Do Not Sell My Personal Information)",
        privacy_p9_1: "Under the CCPA, among other rights, California consumers have the right to:",
        privacy_p9_2: "Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.",
        privacy_p9_3: "Request that a business delete any personal data about the consumer that a business has collected.",
        privacy_p9_4: "Request that a business that sells a consumer's personal data, not sell the consumer's personal data.",
        privacy_p9_5: "If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.",
        privacy_h2_9: "GDPR Data Protection Rights",
        privacy_p10_1: "We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:",
        privacy_p10_2: "The right to access - You have the right to request copies of your personal data. We may charge you a small fee for this service.",
        privacy_p10_3: "The right to rectification - You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.",
        privacy_p10_4: "The right to erasure - You have the right to request that we erase your personal data, under certain conditions.",
        privacy_p10_5: "The right to restrict processing - You have the right to request that we restrict the processing of your personal data, under certain conditions.",
        privacy_p10_6: "The right to object to processing - You have the right to object to our processing of your personal data, under certain conditions.",
        privacy_p10_7: "The right to data portability - You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.",
        privacy_p10_8: "If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.",
        privacy_h2_10: "Children's Information",
        privacy_p11_1: "Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.",
        privacy_p11_2: "Nodehex does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.",
        cookies_title: "We use cookies",
        cookies_p1: "We use cookies and other tracking technologies to improve your browsing experience on our website to analyze our website traffic, and to understand where our visitors are coming from.",
        cookies_allow: "Allow cookies",
        cookies_reject: "Disable cookies"
    },
    nl: {
        title_index: "",
        title_infomgmt: "",
        title_om: "",
        title_reporting: "",
        title_privacy: "",
        header_services: "",
        header_about: "",
        header_contact: "",
        header_home: "",
        services_title: "",
        services_title_infomgmt: "",
        services_content_infomgmt: "",
        read_more: "",
        services_title_om: "",
        services_content_om: "",
        services_title_reporting: "",
        services_content_reporting: "",
        about_title: "",
        about_p1: "",
        about_p2: "",
        why_title: "",
        why_p1: "",
        why_p2: "",
        contact_title: "",
        contact_name: "",
        contact_email: "",
        contact_subject: "",
        contact_message: "",
        footer_tagline: "",
        footer_general: "",
        footer_services: "",
        footer_infomgmt: "",
        footer_reporting: "",
        footer_om: "",
        footer_about: "",
        footer_contact: "",
        footer_privacy: "",
        infomgmt_intro: "",
        infomgmt_cims_header: "",
        infomgmt_cims_text: "",
        infomgmt_pis_header: "",
        infomgmt_pis_text: "",
        infomgmt_edms_header: "",
        infomgmt_edms_text_intro: "",
        infomgmt_edms_header2: "",
        infomgmt_edms_li1: "",
        infomgmt_edms_li2: "",
        infomgmt_edms_li3: "",
        infomgmt_edms_li4: "",
        infomgmt_edms_li5: "",
        infomgmt_edms_li6: "",
        infomgmt_dmp_header: "",
        infomgmt_dmp_text_intro: "",
        infomgmt_dmp_li1: "",
        infomgmt_dmp_li2: "",
        infomgmt_dmp_li3: "",
        infomgmt_dihihc_header: "",
        infomgmt_dihihc_text: "",
        infomgmt_mitigate_text_intro: "",
        infomgmt_mitigate_li1: "",
        infomgmt_mitigate_li2: "",
        infomgmt_mitigate_li3: "",
        infomgmt_mitigate_li4: "",
        infomgmt_reporting_link: "",
        om_intro: "",
        om_p1: "",
        om_p2: "",
        om_h5_1: "",
        om_sysdesc_header: "",
        om_sysdesc_text: "",
        om_spec_header: "",
        om_spec_text: "",
        om_dmgd_header: "",
        om_dmgd_text: "",
        om_seqops_header: "",
        om_seqops_text: "",
        om_contact_link: "",
        reporting_intro: "",
        reporting_p1: "",
        reporting_p2: "",
        reporting_li_edms: "",
        reporting_li_detc: "",
        reporting_li_cde: "",
        reporting_li_bimproj: "",
        reporting_li_comenv: "",
        reporting_li_bimcom: "",
        reporting_li_mprf: "",
        reporting_li_extranet: "",
        reporting_p3: "",
        reporting_p4: "",
        reporting_contact: "",
        privacy_h1: "",
        privacy_p1_1: "",
        privacy_p1_2: "",
        privacy_p1_3: "",
        privacy_h2_1: "",
        privacy_p2_1: "",
        privacy_h2_2: "",
        privacy_p3_1: "",
        privacy_p3_2: "",
        privacy_h2_3: "",
        privacy_p4_1: "",
        privacy_li_1: "",
        privacy_li_2: "",
        privacy_li_3: "",
        privacy_li_4: "",
        privacy_li_5: "",
        privacy_li_6: "",
        privacy_li_7: "",
        privacy_h2_4: "",
        privacy_p5_1: "",
        privacy_h2_5: "",
        privacy_p6_1: "",
        privacy_p6_2: "",
        privacy_p6_3: "",
        privacy_h2_6: "",
        privacy_p7_1: "",
        privacy_p7_2: "",
        privacy_p7_3: "",
        privacy_h2_7: "",
        privacy_p8_1: "",
        privacy_p8_2: "",
        privacy_h2_8: "",
        privacy_p9_1: "",
        privacy_p9_2: "",
        privacy_p9_3: "",
        privacy_p9_4: "",
        privacy_p9_5: "",
        privacy_h2_9: "",
        privacy_p10_1: "",
        privacy_p10_2: "",
        privacy_p10_3: "",
        privacy_p10_4: "",
        privacy_p10_5: "",
        privacy_p10_6: "",
        privacy_p10_7: "",
        privacy_p10_8: "",
        privacy_h2_10: "",
        privacy_p11_1: "",
        privacy_p11_2: "",
        cookies_title: "",
        cookies_p1: "",
        cookies_allow: "",
        cookies_reject: ""
    },
    se: {
        title_index: "Nodehex",
        title_infomgmt: "Nodehex - Informationshantering",
        title_om: "Nodehex - Drift- och underhållsmanualer",
        title_reporting: "Nodehex - Rapporter och analyser",
        title_privacy: "Nodehex - Integritetspolicy",
        header_services: "TJÄNSTER",
        header_about: "OM",
        header_contact: "KONTAKT",
        header_home: "HEM",
        services_title: "TJÄNSTER",
        services_title_infomgmt: "INFORMATIONSHANTERING",
        services_content_infomgmt: "Hantering och koordinering av digitala tillgångar, data och rådgivning gällande processer och implementering av informationshanteringssystem för datacenter i hyperskala, bostads- och specialistinfrastruktur.",
        read_more: "LÄS MER",
        services_title_om: "DoU-MANUALER",
        services_content_om: "Underhåll av högkvalitativa byggnader kräver ofta enastående grundinformation. Vi hanterar manualprocessen och säkrar att er driftavdelning står på stadig grund.",
        services_title_reporting: "RAPPORTER & ANALYSER",
        services_content_reporting: "Spårning av utförsäljning, analyser av nyckelpunkter och tydliga, lättsmälta informationspaneler säkerställer att ni har informationen ni behöver för att noga följa dokumentationens utveckling.",
        about_title: "OM NODEHEX",
        about_p1: "Nodehex är en specialistgrupp för informationshantering av datacenter i hyperskala och kommersiella byggprojekt. Vårt team har bred erfarenhet av att leverera och hantera dokumentationstjänster för ett stort antal projekt inom datacenter i hyperskala samt den specialistinfrastruktur, de kontor och övriga kringliggande byggnader som möjliggör dem. Vi simplifierar processen genom att förstå kundbehov och krav samt ta bort oklarheter kring dokumentation för att implementera en struktur som säkerställer ett bestående intryck av informationshanteringen genom alla uppdragskritiska system.",
        about_p2: "Våra tjänster fokuserar på att tillhandahålla en högkvalitativ, datadriven och framtung insats för att säkerställa effektiv leverans från design till avveckling. Detta kombineras med support under första driftåret, en smidig övergång till högkvalitativ dokumentation för driftavdelningen att använda, en anläggning är bara så bra som informationen den understöds av.",
        why_title: "VARFÖR NODEHEX",
        why_p1: "Nodehex är ett tvärvetenskapligt, multikulturellt team av informationshanteringsspecialister, datavetare, mjukvaruutvecklare och formgivare som har arbetat inom bygg- och IT-branscherna under de senaste 10 åren.",
        why_p2: "Vår expertis har utvecklats genom storskaliga infrastrukturprojekt, byggnader för datacenter i hyperskala och specialistanläggningar. Vi strävar efter att utnyttja framväxande teknologier inom den digitala byggsektorn för att extrahera det enorma värde av projektdatat och tillhandahålla expertkonsultation av process- och informationshantering.",
        contact_title: "KONTAKT",
        contact_name: "Namn",
        contact_email: "E-post",
        contact_subject: "Ämne",
        contact_message: "Meddelande",
        footer_tagline: "Construction data, digitalised",
        footer_general: "Allmänt",
        footer_services: "Tjänster",
        footer_infomgmt: "INFORMATIONSHANTERING",
        footer_reporting: "RAPPORTER & ANALYSER",
        footer_om: "DoU-MANUALER",
        footer_about: "OM",
        footer_contact: "KONTAKTA NODEHEX",
        footer_privacy: "INTEGRITET",
        infomgmt_intro: "Nodehex har arbetat inom informationshanteringsbranschen i ett årtionde. Vår erfarenhet är bred och täcker alla möjliga leverabler och expertiser i området, från datakvalitet och systemimplementation till storskalig rapportering och analys. Vi har ett tvärvetenskapligt synsätt som kombinerar expertis inom digital byggnadskonst med datavetenskap och mjukvaruutveckling för att garantera att vi levererar högkvalitativa resultat baserat på de dynamiska behoven i era projekt.",
        infomgmt_cims_header: "Kärntjänster inom informationshantering",
        infomgmt_cims_text: "Våra tjänster fokuserar på leverans av digital byggnadskonst genom hela projektets livscykel, uppdelat i tre kärnkompetenser: projektstarts, rapportering och överlämning.",
        infomgmt_pis_header: "Projektstartstjänster",
        infomgmt_pis_text: "Överlämning är oftast den sista punkten att pricka av under slutfasen av byggnationen och driftsättningen, snarare än en framtung del av arbetet som börjar i designfasen. Majoriteten av problemen som kan uppstå under överlämningen mitigeras av ett erfaret informationshanteringsteam som utvecklar korrekta planer, processer och rutiner, vilket möjliggör en progressiv överlämning snarare än en massiv uppgift i projektets slutskede.",
        infomgmt_edms_header: "Elektroniska dokumenthanteringssystem",
        infomgmt_edms_text_intro: "Vårt team har över 15 års erfarenhet inom industriledande elektroniska dokumenthanteringssystem (EDMS) på en administratörs- och utvecklarnivå, vilket är en kritisk komponent för stora projekt och effektiv hantering av digital information.",
        infomgmt_edms_header2: "Våra tjänster täcker följande områden inom <span class=\"yellow-text\">EDMS-implementering</span>:",
        infomgmt_edms_li1: "Uppsättning och utveckling på projektnivå",
        infomgmt_edms_li2: "Utbildning av ämnesexperter, utveckling och leverans",
        infomgmt_edms_li3: "Utbildning av projektteamet baserat på behovsanalys",
        infomgmt_edms_li4: "Kärnbehovsanalys av metadata för alla intressenter: kund, entreprenörer och underleverantörer.",
        infomgmt_edms_li5: "Fullt levererbar förpopulering under projektets startskede för att möjliggöra exakt och tydlig rapportering.",
        infomgmt_edms_li6: "Standardiserade arbetsflöden baserade på branschpraxis.",
        infomgmt_dmp_header: "Dokumenthanteringsplaner",
        infomgmt_dmp_text_intro: "Vårt team har erfarenhet av att författa, granska, godkänna och implementera dokumenthanteringen i storskaliga projekt. Vi förstår kundbehoven samt era krav och översätter dessa till effektiva processer och rutiner för projektgenomförandet. Vi erbjuder:",
        infomgmt_dmp_li1: "Färdigförfattade dokumenthanteringsplaner inklusive kundbehov och koordinering av gransknings- och godkännandeprocesserna.",
        infomgmt_dmp_li2: "Nedbrytning och detaljering av kärnsystemsuppsättningen samt krav, arbetsflöden, ledningskrav och överlämningsprocesser i planen.",
        infomgmt_dmp_li3: "Visuella arbetsflöden för att koncist förmedla projektprocesserna.",
        infomgmt_dihihc_header: "Huvudleveransregister, överlämningsregister och -koordinering",
        infomgmt_dihihc_text: "Att förstå informationsleveransen är centralt för att hålla säljare, leverantörer och underleverantörer ansvariga för överlämning. Att få dessa processer på plats och utföra dem under projektets uppstartsfaser garanterar en enkel överlämning och tydligt ansvar.",
        infomgmt_mitigate_text_intro: "Vi mitigerar risken för sen leverans och försenad överlämning genom att:",
        infomgmt_mitigate_li1: "Initiera registren för <span class=\"yellow-text\">huvudleverans</span> och <span class=\"yellow-text\">överlämning</span> samt utveckla dessa kontinuerligt och parallelt från projektstart.",
        infomgmt_mitigate_li2: "Koordinera med underleverantörer för att populera och utveckla registren, för att säkerställa full insyn och förståelse.",
        infomgmt_mitigate_li3: "Integrera med driftsättningsteamen för att projektera och supportera driftsättningsdokumentationen och dess överlämning.",
        infomgmt_mitigate_li4: "Koordinera överlämningen, inklusive spårning av alla PDF:er och övriga leverabler över flera system och in i klientens system.",
        infomgmt_reporting_link: "För mer information om våra rapporteringstjänster, navigera till vår <a href=\"reporting-analytics.html\" class=\"content-link\">tjänstesida för rapporter och analyser</a>.",
        om_intro: "Drift- och underhållsmanualer är grundvalen i ett högpresterande driftteam. De är heltäckande dokument som tillhandahåller all nödvändig information gällande en byggnads system, och tillgårna i dessa system, i klintens datacenter och uppdragskritiska infrastruktur.",
        om_p1: "Med tanke på den ständigt växande omfattningen av informationshantering samt dess användbarhet för datautnyttjande av högt värde för design-, bygg-, drift-, och ägarteamen, är det imperativt att identifiera och, ännu viktigare, förbättra datainsamlingen för drift- och underhållsmanualer. Under byggnationen av ett datacenter i hyperskala, kan den rena mängden av information som produceras vara förbluffande, och att hitta effektiva sätt att hantera datat för överlämning - särskilt med tanke på att moderna överlämningspaket för datacenter i hyperskala kan innehålla över 50 000 dokument - kan vara utmanande.",
        om_p2: "Koordinering och spridning av denna information inom ett projekt kräver kunskap om etapperna för ett datacenter i hyperskala och dess kringliggande byggnader, så som transformatorstationer och driftbyggnader och en djup förståelse av informationslivscykeln, kvalitetsintegration och projekthanteringspraxis vid rätt tillfälle för att säkerställa optimalt resultat.",
        om_h5_1: "En typisk DoU-manual inkluderar en mängd information, generellt baserat på system i den driftsatta byggnaden, så som:",
        om_sysdesc_header: "Systembeskrivning",
        om_sysdesc_text: "Kundbeskrivning och -krav som preciserar den specifika systeminformationen som understöder generella produktbehov",
        om_spec_header: "Specifikationer",
        om_spec_text: "Kundspecifikationer och -krav gällande specifika systemdetaljer som understöder allmänna produktbehov",
        om_dmgd_header: "Ritningar, modeller och grafisk data",
        om_dmgd_text: "Referensmodeller och inbäddad information som hänför sig till design- och byggteamens krav på specificerad detaljnivå från kundens informationsbehov",
        om_seqops_header: "Driftsekvenser",
        om_seqops_text: "Information gällande säker uppstart, normal systemdrift och felsäkert förfarande och anläggning",
        om_contact_link: "På Nodehex kan vi författa, underhålla och implementera en mängd olika lösningar för att säkerstella att överlämning, drift, och informationen som krävs för att underhålla systemen i ert projekt kan genomföras både säkert och effektivt. Vare sig detta gäller helförfattad och koordinerad projektinformation, konsolidering och uppdatering av existerande manualer eller skräddarsydda lösningar för era behov, <a href=\"index.html#contact\" class=\"content-link\">så kan vi hjälpa till</a>.",
        reporting_intro: "Det enorma värdet i datacenter finns i dess primärfunktioner, lagringen, processeringen och spridningen av data och kritiska applikationer. Medan datacenter använder data effektivt och är kapabla till att extrahera värdet av denna data, har byggteam ofta svårigheter att extrahera potentialen av datat som genereras under ett projekt.",
        reporting_p1: "Medan projektkontrollteam ofta utmärker sig på att hantera kostnader, handel och schemaläggning, och det ofta finns någon form av analys fokuserad på BIM, kvalitet och dokumentation, är den fulla potentialen av dessa tjänster aldrig faktiskt uppnådd. Projekt har ofta skrymmande och analoga utdrags-, överförings-, och laddningsprocesser som inte tillhandahåller flexibilitet och realtidsrapportering på grund av begränsningar i verktyg, teknik eller allmän brist på sakkunskap gällande datavetenskap och -implementering.",
        reporting_p2: "I alla projekt finns det ofta minst ett par system som täcker <span class=\"yellow-text\">BIM</span>, <span class=\"yellow-text\">kvalitet</span> och <span class=\"yellow-text\">dokumentation</span>",
        reporting_li_edms: "Elektroniskt dokumenthanteringssystem (EDMS)",
        reporting_li_detc: "Documentum, Aconex, Viewpoint 4Projects, EnterpriseBridge, osv.",
        reporting_li_cde: "Gemensam datamiljö",
        reporting_li_bimproj: "BIM360, ProjectWise, Procore, BIMPLUS, osv.",
        reporting_li_comenv: "Driftsättningsmiljö",
        reporting_li_bimcom: "BIM360 Field, driftsättningsspårning, osv.",
        reporting_li_mprf: "Projekthuvudmappar",
        reporting_li_extranet: "Mappstrukturer, spårare, kalkylblad, osv baserade i molnet annat nätverk.",
        reporting_p3: "Vårt team har erfarenheten och sakkunskapen som krävs för att använda applikationsprogrammeringsgränssnitt (API:er), processer för extrahering, transformering och inläsning (ETL) samt helautomatiserad direktrapportering för att säkerställa att ni kan demonstrera var blockerare och problem kan hittas och extrahera mervärdet från dessa datauppsättningar som lämnas bakom i de flesta projekt.",
        reporting_p4: "Dessutom tillhandahåller vi iögonfallande analyser och virtualiseringar för att säkerställa att datan vi extraherat tillhandahåller tydliga och synliga detaljer gällande var ni är i projektet, hur den progressiva överlämningen utvecklar sig samt var varje detalj kan hittas i projektets datamiljö.",
        reporting_contact: "För mer information, <a href=\"index.html#contact\" class=\"content-link\">kontakta oss</a> så tar vi fram en lösning som passar era behov och kravställningar.",
        privacy_h1: "Nodehex AB:s integritetspolicy",
        privacy_p1_1: "På Nodehex AB, tillgängligt via https://nodehex.com, är våra besökares integritet en av våra största prioriteter. Denna integritetspolicy innehåller de typer av information som samlas samt hur de används av oss.",
        privacy_p1_2: "Tveka inte att kontakta oss om du har funderingar eller frågor gällande vår integritetspolicy.",
        privacy_p1_3: "Integritetspolicyn gäller endast vår verksamhet via - och besökare till - denna webbplats, samt informationen som delges Nodehex AB via den. Policyn gäller inte information insamlad på något sätt utanför denna webbplats (t.ex. via e-post eller personligt möte).",
        privacy_h2_1: "Samtycke",
        privacy_p2_1: "Genom att använda denna webbplats, samtycker du härmed till denna integritetspolicy och dess villkor.",
        privacy_h2_2: "Informationen vi samlar",
        privacy_p3_1: "Den personliga information vi ber dig delge, samt anledningen till att du ombeds delge denna, klargörs i samband med att vi efterfrågar den.",
        privacy_p3_2: "Om du kontaktar oss direkt, är det möjligt att vi erhåller ytterligare information om dig, så som ditt namn, e-postadress, telefonnummer, innehållet i meddelandet du skickar inklusive eventuella bilagor och övrig information du väljer att delge.",
        privacy_h2_3: "Hur vi använder din information",
        privacy_p4_1: "Vi använder informationen vi mottar på olika sätt, inklusive för att:",
        privacy_li_1: "Tillhandahålla, driftsätta och underhålla vår webbplats",
        privacy_li_2: "Förbättra, personifiera och expandera vår webbplats",
        privacy_li_3: "Förstå och analysera hur du använder vår webbplats",
        privacy_li_4: "Utveckla nya produkter, tjänster, funktioner och funktionalitet",
        privacy_li_5: "Kommunicera med dig, antingen direkt eller via en av våra partner, inklusive för kundtjänst, för att förse er med uppdateringar och annan information som avser webbplatsen, samt i marknadsförings- och kampanjsyften.",
        privacy_li_6: "Skicka e-post till dig",
        privacy_li_7: "Upptäcka och förebygga bedrägeri",
        privacy_h2_4: "Loggfiler",
        privacy_p5_1: "Nodehex AB följer en standardprocedur gällande användning av loggfiler. Dessa loggfiler loggar besökare när de besöker webbplatser. Alla hostingbolag gör detta som del av hostingtjänsternas analyser. Informationen samlad i loggfilerna inkluderar IP-adresser, webbläsartyp, internetleverantör, datum- och tidsstämpel, hänvisande och lämnande webbsidor samt eventuellt antalet klick. Detta är inte länkat till information som är personligt identifierbar. Syftet med informationen är trendanalys, webbplatsadministration, spårning av användares rörelser genom webbplatsen samt insamling av demografisk information.",
        privacy_h2_5: "Kakor och webbfyrar",
        privacy_p6_1: "Precis som de flesta andra webbplatser, använder Nodehex AB kakor ('cookies'). Dessa kakor används för att lagra information gällande besökares inställningar samt den eller de sidor på webbplatsen som användaren har hämtat eller besökt. Informationen används för att optimera användarnas upplevelse genom att anpassa webbplatsens innehåll efter webbläsartyp och/eller annan information.",
        privacy_p6_2: "För mer information gällande kakor, vänligen",
        privacy_p6_3: "läs mer på Cookie Consent:s webbplats (engelska)",
        privacy_h2_6: "Reklampartners integritetspolicyer",
        privacy_p7_1: "Läs här för att få mer information om Nodehex AB:s reklampartners.",
        privacy_p7_2: "Tredjeparts reklamservrar och reklamnätverk använder teknologier så som kakor, JavaScript eller webbfyrar som används i deras respektive reklamplatser eller -länkar som finns på Nodehex AB:s webbplats, och skickas till användarens webbläsare. De får automatiskt tillgång till din IP-adress när detta sker. Dessa teknologier används för att mäta deras reklamkampanjers effektivitet och/eller för att personifiera reklaminnehållet som du ser på de webbplatser du besöker.",
        privacy_p7_3: "Notera att Nodehex AB inte har tillgång eller kontroll över kakor som används av tredje parts reklampartner.",
        privacy_h2_7: "Integritetspolicy av tredje part",
        privacy_p8_1: "Nodehex AB:s integritetspolicy gäller inte för andra reklamleverantörer eller webbplatser. Därför rådger vi dig att läsa respektive tredje parts integritetspolicyer för mer information. Dessa kan inkludera deras användningsområden och instruktioner om hur man väljer bort olika val.",
        privacy_p8_2: "Du kan välja att stänga av kakor genom din webbläsares inställningar. För att läsa mer om kakhanteringen i olika webbläsare råder vi dig att besöka respektive webbläsares webbplats.",
        privacy_h2_8: "CCPA integritetsrättigheter ('sälj inte min personliga information')",
        privacy_p9_1: "Under CCPA, samt andra rättigheter, har konsumenter i delstaten Kalifornien i USA rätt att:",
        privacy_p9_2: "Begära att ett företag som samlar en konsuments personliga data ger ut kategorierna och delar av den specifika personliga data som företaget har samlat om konsumenten.",
        privacy_p9_3: "Begära att ett företag raderar all personlig data som företaget har samlat om den specifika konsumenten.",
        privacy_p9_4: "Begära att företag som säljer konsumenters personliga data, inte säljer den specifika konsumentens personliga data.",
        privacy_p9_5: "Om du gör en sådan begäran har vi en månad på oss att svara dig. Vänligen kontakta oss om du vill utnyttja någon av dessa rättigheter.",
        privacy_h2_9: "Rättigheter under dataskyddsförordningen (GDPR)",
        privacy_p10_1: "Vi vill säkerställa att du är fullt medveten om dina dataskyddsrättigheter. Alla användare är berättigade följande:",
        privacy_p10_2: "Rätten till tillgång - du har rätten att begära kopior på dina personuppgifter. Vi kan ta ut en mindre avgift för denna tjänst.",
        privacy_p10_3: "Rätten till rättning - du har rätten att begära rättning av information du anser vara inkorrekt eller felaktig. Du har också rätten att begära att vi kompletterar information du anser vara ofullständig.",
        privacy_p10_4: "Rätten till radering - du har rätten att begära radering av dina personuppgifter, under vissa förutsättningar.",
        privacy_p10_5: "Rätten till behandlingsbegränsning - du har rätten att begära begränsning av personuppgiftsbehandlingens omfattning, under vissa förutsättningar.",
        privacy_p10_6: "Rätten till behandlingsinvändning - du har rätten att invända mot vår behandling av personuppgifter, under vissa förutsättningar.",
        privacy_p10_7: "Rätten till dataportabilitet - du har rätten att begära dataöverföring av personuppgifterna vi samlat om dig till en annan organisation, eller direkt till dig, under vissa förutsättningar.",
        privacy_p10_8: "Om du gör en sådan begäran har vi en månad på oss att svara dig. Vänligen kontakta oss om du vill utnyttja någon av dessa rättigheter.",
        privacy_h2_10: "Information för barn",
        privacy_p11_1: "En annan prioritet för oss är att skydda barn när de använder internet. Vi uppmanar föräldrar och målsmän att observera, delta och/eller övervaka och vägleda barnens aktivitet på internet.",
        privacy_p11_2: "Nodehex AB samlar inte till vår vetskap personuppgifter om barn under 13 år. Om du misstänker att ditt barn har delgett sådan information på vår webbplats, uppmanar vi dig att genast kontakta oss för att ska kunna radera sådan information från våra register snarast möjligt.",
        cookies_title: "Vi använder kakor",
        cookies_p1: "Vi använder kakor ('cookies') och andra spårningsverktyg för att förbättra din upplevelse av vår webbplats och analysera webbplatstrafik, inklusive land.",
        cookies_allow: "Tillåt",
        cookies_reject: "Neka"
    }
}
